### ISSUE TITLE
Samsung Internet has all permissions for contacts picker api('contacts' in navigator && 'ContactsManager' in window). But after call navigator.contacts.select I get 'TypeError: Unable to open a contact selector'

### ISSUE THREAD

**Issue by tkachuks** [w3c/contact-picker#33]
Related to [this issue](https://github.com/SamsungInternet/support/issues/105)

**Comment by Doc999tor** [comment]
Same case: Samsung Browser passes the checks but fails to open the contact picker 
Very annoying issue - I had to just block Samsung Browser by user agent
Any help/clarification is very appreciated

**Comment by mykolaelement** [comment]
face same issue

**Comment by tomayac** [comment]
CC: @torgo from Samsung Internet for triage.

**Comment by marcoscaceres** [comment]
Given this is a browser specific bug (https://github.com/SamsungInternet/support/issues/105), we should close this.
