### ISSUE TITLE
Migrate into a working group

### ISSUE THREAD

**Issue by xfq** [w3c/contact-picker#37]
There is interest within the Devices and Sensors WG for adding this specification to our list of tentative deliverables. This does not mean that work will immediately move into the working group but that a reference to this specification will be added to the working group's charter so that such a migration will be possible at a later date.

See discussions in https://github.com/w3c/dap-charter/issues/97

@LJWatson @cwilso @yoavweiss @travisleithead, as chairs of the WICG do you concur?

**Comment by yoavweiss** [comment]
LGTM

**Comment by samuelweiler** [comment]
Being considered as part of https://github.com/w3c/strategy/issues/267

**Comment by plehegar** [comment]
@rayankans any concern with moving the spec to the Web Apps Working Group instead of having in Devices and Sensors? See 
https://github.com/w3c/strategy/issues/267#issuecomment-853168651 and  https://github.com/w3c/strategy/issues/267#issuecomment-871762299 for why it would make more sense to have it in WebApps.

**Comment by marcoscaceres** [comment]
@yoavweiss, could you add me as admin to this repo as I'd like to work on this spec? We haven't heard back from @rayankans unfortunately but would still like to move it over to the W3C.

**Comment by rayankans** [comment]
Sorry for the delayed response, no issues from my end to move the spec to the Web Apps WG.

@marcoscaceres I've sent you an invite for an admin role in the repo

**Comment by marcoscaceres** [comment]
Oh hey! Welcome back 🤗 though we’d lost you. Awesome!

**Comment by plehegar** [comment]
note that the current proposal is to make it a joint deliverable between DAS and WebApps.

**Comment by marcoscaceres** [comment]
Closing as this is now a joint deliverable with WebApps and DAP.
