### ISSUE TITLE
Prepare for W3C FPWD

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/contact-picker#50]
To prepare for publication, we need to change the bikeshed config to use the W3C FPWD template... and probably a few other things. 

As we are not expecting any objections, we should aim for 4th October as the publication date.

**Comment by marcoscaceres** [comment]
@siusin, can I leave this for you to handle from here together with @rayankans?

**Comment by siusin** [comment]
Sure, Marcos. I'll work with @rayankans and our SysTeam, to publish this joint deliverable.

/cc @deniak @jennyliang220

**Comment by himorin** [comment]
published.
