### ISSUE TITLE
Matching ContactAddress fields to autofill attributes

### ISSUE THREAD

**Issue by jcayzac** [w3c/contact-picker#71]
Hi,

There is no clear mapping between the fields of [`PaymentAddress`](https://w3c.github.io/payment-request/#physical-addresses) and the values accepted by the [`autocomplete`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) attribute for shipping and billing addresses: `PaymentAddress` uses descriptive semantics while `autocomplete` leaves the semantics open to regional variations. Is there a suggested mapping between the two?

Thank you.

**Comment by ianbjacobs** [comment]
This issue was raised in Payment Request, but closed once we removed addresses from that API. Since the features are now part of Contact Picker, we are transferring the issue here.

**Comment by rsolomakhin** [comment]
Hi, can this issue be closed? It appears the question[1] was answered.

[1] Question was "Is there a suggested mapping between the two?".

**Comment by jcayzac** [comment]
@rsolomakhin Sure.
